
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTEROBJECT_H
#define MASTEROBJECT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 masterobject_valueRangeTest (UNS8 typeValue, void * value);
const indextable * masterobject_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data masterobject_Data;
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/

#endif // MASTEROBJECT_H
